Add VirtualAxis
Leafwing-Studios/leafwing-input-manager pull request #277
Opened 2022-10-26 20:38 UTC by johanhelsing

Similar to `VirtualDPad`, but for one axis only.

Closes: #216

2022-10-26 21:27 UTC, johanhelsing commented on src/axislike.rs
> +    /// The input that represents the down direction in this virtual DPad
Oops, made some copy paste errors here.

2022-10-26 21:27 UTC, alice-i-cecile commented on src/axislike.rs
> +    /// The input that represents the up direction in this virtual DPad
```suggestion
    /// The input that represents the down direction in this virtual axis
```

2022-10-26 21:27 UTC, alice-i-cecile commented on src/axislike.rs
> +    /// The input that represents the down direction in this virtual DPad
```suggestion
    /// The input that represents the up direction in this virtual axis
```

2022-10-26 21:28 UTC, alice-i-cecile requested changes
Solid work! A minor doc suggestion, and this needs to be added to the change log.

2022-10-28 13:20 UTC, alice-i-cecile approved these changes

2022-10-28 13:23 UTC, merged