Do not trigger mouse actions on button click
Leafwing-Studios/leafwing-input-manager pull request #355
Opened 2023-06-24 21:00 UTC by Shatur

2023-06-25 00:41 UTC, alice-i-cecile approved these changes

2023-06-25 00:41 UTC, alice-i-cecile requested changes
Can you add a changelog entry?

2023-06-25 09:00 UTC, Shatur commented
Done!
I also changed interaction check for any interaction.

2023-06-26 15:35 UTC, alice-i-cecile approved these changes
Good, this is a nice simple fix for now.

2023-06-26 16:07 UTC, merged