Add Inversion to SingleAxis, DualAxis, and VirtualDPad
Leafwing-Studios/leafwing-input-manager pull request #362
Opened 2023-06-30 15:23 UTC by SignalWalker

Fixes #247.

Adds `inverted`, `inverted_x`, and `inverted_y` builder-style functions for `SingleAxis`, `DualAxis`, and `VirtualDPad`, where appropriate. The `SingleAxis` implementation uses an `inverted` field, the `DualAxis` implementation just inverts its internal axes, and the `VirtualDPad` implementation swaps the relevant inputs.

## Todo
- [ ] Write tests
- [ ] Better documentation?

2023-06-30 16:29 UTC, alice-i-cecile commented on src/axislike.rs
> +    /// Returns this [`DualAxis`] with inverted axes.
```suggestion
    /// Returns this [`DualAxis`] with both axes inverted.
```

2023-06-30 16:29 UTC, alice-i-cecile requested changes
Solid :) Changelog entry and a couple tests and this looks good to me.

2023-06-30 17:31 UTC, SignalWalker commented
> Solid :) Changelog entry and a couple tests and this looks good to me.

Cool, thanks. `CONTRIBUTING.md` says to put changes into `CHANGELOG.md`, which doesn't exist -- I assume it should be `RELEASES.md`?

2023-06-30 19:44 UTC, alice-i-cecile commented
That's correct. Thanks for pointing that out; I'll update it!

2023-07-02 16:43 UTC, alice-i-cecile approved these changes

2023-07-02 16:49 UTC, merged