Add back `bevy_egui` to LWIM 0.11
Leafwing-Studios/leafwing-input-manager pull request #409
Opened 2023-11-05 22:13 UTC by 100-TomatoJuice

I tested `minimal.rs` using the egui feature just to make sure nothing broke, and it works.

2023-11-05 22:23 UTC, alice-i-cecile requested changes
Can you update the release notes and the main Cargo.toml to a point release here too?

2023-11-05 22:24 UTC, 100-TomatoJuice commented
Like changing the LWIM version to 0.11.1 and adding to the release notes that egui was added back?

2023-11-06 03:24 UTC, alice-i-cecile commented
Correct. I don't bother with the minor versions for the macro crate.

2023-11-06 14:25 UTC, alice-i-cecile approved these changes

2023-11-06 14:25 UTC, merged