Replace `ToggleActions<A>` with per-action disable flags
Leafwing-Studios/leafwing-input-manager pull request #456
Opened 2024-01-29 02:19 UTC by benfrankel

# Objective

Fixes https://github.com/Leafwing-Studios/leafwing-input-manager/issues/446.

# Solution

Don't disable the systems that update action state. Instead, include a `disabled` flag per action within `ActionState<A>`. While `disabled` is `true`, an action will always read as released, regardless of its actual state.

Other benefits:
- Replaces `ToggleActions<A>`, making the API surface area smaller.
- Supports granular enabling / disabling between:
  - The individual actions of an `ActionState<A>`
  - Different entities with the same `ActionState<A>` component type
  - Resource vs component versions of `ActionState<A>`
- Keeps the action update logic simple and consistent by only affecting how the state is read, not how it's written.

Alternative approach: https://github.com/Leafwing-Studios/leafwing-input-manager/pull/454.

2024-01-29 02:45 UTC, Shute052 commented
It seems more suitable for me because my solution is just to keep the public API from making significant changes.

2024-01-29 03:02 UTC, Shute052 commented
Would it be better to add a `disabled` flag and a `toggle_all()` function within the `ActionState` to ensure similarity with the existing public API?

2024-01-29 03:07 UTC, benfrankel commented
> Would it be better to add a `disabled` flag and a `toggle_all()` function within the `ActionState` to ensure similarity with the existing public API?

In addition to the per-action flags, or instead of them? I was originally going to only put one `disabled` flag in `ActionState` itself, but while implementing that I figured per-action would be a little bit easier to implement (because there are multiple places that access `action_data` directly) and would give the user more control.

2024-01-29 03:19 UTC, Shute052 commented
Ahh, the newly added `enabled()` and `disabled()` meets my needs, which weren't there before.

2024-03-16 02:42 UTC, benfrankel commented
Rebased and fixed merge conflicts.

2024-06-01 04:00 UTC, atlv24 commented
This doesn't trigger just_pressed/just_released when enabling/disabling a currently-pressed button, does it?

2024-06-01 04:21 UTC, benfrankel commented
> This doesn't trigger just_pressed/just_released when enabling/disabling a currently-pressed button, does it?

Nope, while an action is disabled, it will _strictly_ read as `released` and nothing else.

2024-06-01 05:06 UTC, atlv24 commented
That might be undesirable, whats the justification? I would expect disabling a pressed button to release it. This would allow multiple `just_pressed` frames to be observed without any `just_released` frames in-between, or vice-versa

2024-06-01 05:12 UTC, benfrankel commented
The reasoning is elaborated on in https://github.com/Leafwing-Studios/leafwing-input-manager/issues/446 and https://github.com/Leafwing-Studios/leafwing-input-manager/issues/416.

It may seem wrong but the alternative (the current behavior) is also wrong. An action wasn't actually "just pressed" just because you re-enabled it, and you don't want re-enabling an action to trigger all of its `do_thing.run_if(action_just_pressed)` systems.

2024-06-01 05:19 UTC, atlv24 approved these changes

2024-06-01 15:51 UTC, alice-i-cecile requested changes
This needs release notes before it can be merged. I'm in favor of this design though, so I'll write it myself in the preparation for the release if you don't have a chance.

2024-06-01 19:07 UTC, benfrankel commented
Wrote release notes.

2024-06-01 19:54 UTC, alice-i-cecile approved these changes

2024-06-01 20:10 UTC, merged