Add missing handling for `ActionState::consumed`
Leafwing-Studios/leafwing-input-manager pull request #480
Opened 2024-02-21 00:04 UTC by Shute052

Missing handling with `ActionState::consumed` was added back, which was overlooked in #450.

![image](https://github.com/Leafwing-Studios/leafwing-input-manager/assets/22796024/eab5dd3e-0624-48a0-b7e2-27414dc01371)

To be specific, `ActionState::press(Action)` takes `consumed` into account, whereas `ActionData::state::press(Action)` did not.

2024-02-21 00:09 UTC, Shute052 commented
Both 0.12.2 and 0.13.1?

2024-02-21 00:12 UTC, alice-i-cecile commented on RELEASES.md
> +## Version 0.12.2
This should probably be `0.13.1`. I don't think this is impactful enough to backport without others asking for it.

2024-02-21 00:12 UTC, alice-i-cecile requested changes
Change itself looks good, but let's aim for 0.13.1 instead.

2024-02-21 00:14 UTC, Shute052 commented
Also bump the version number

2024-02-21 01:09 UTC, alice-i-cecile approved these changes

2024-02-21 01:09 UTC, merged

2024-02-23 07:05 UTC, Shute052 commented
This fixed #443